export default {
  "textarea_configs": [
    {
      "id": "desc1",
      "width": "156pt",
      "height": "160pt",
      "x": "36pt",
      "y": "18pt",
      "font_size": "10pt",
      "padding": "3pt",
      "bold": false,
      "border": true,
      "font_weight": "normal",
      "alignment": "left",
      "default_text": "CHAIN LINK FABRIC:\n\nLINE/GATE/TERMINAL POSTS:\n\nTOP RAIL:\nBOTTOM TENSION WIRE:\nGATE AND BRACE:\nTIE WIRES:\nFITTINGS AND ACCESSORIES:\n\n*NOTE:"
    },
    {
      "id": "desc2",
      "width": "490pt",
      "height": "160pt",
      "x": "192pt",
      "y": "18pt",
      "font_size": "10pt",
      "padding": "3pt",
      "bold": false,
      "border": true,
      "font_weight": "normal",
      "alignment": "left",
      "default_text": ""
    },
    {
      "id": "title",
      "width": "646pt",
      "height": "32pt",
      "x": "36pt",
      "y": "178pt",
      "font_size": "18pt",
      "padding": "3pt",
      "bold": true,
      "border": true,
      "font_weight": "bold",
      "alignment": "center",
      "default_text": "{}\u2019-0\u201d HIGH CHAIN LINK FENCE"
    },
    {
      "id": "date",
      "width": "164pt",
      "height": "28pt",
      "x": "682pt",
      "y": "18pt",
      "font_size": "14pt",
      "padding": "3pt",
      "bold": false,
      "border": true,
      "font_weight": "normal",
      "alignment": "center",
      "default_text": "//"
    },
    {
      "id": "scale",
      "width": "164pt",
      "height": "28pt",
      "x": "682pt",
      "y": "46pt",
      "font_size": "14pt",
      "padding": "3pt",
      "bold": false,
      "border": true,
      "font_weight": "normal",
      "alignment": "center",
      "default_text": "SCALE: \u00bd\u201d = 1\u2019-0\u201d"
    },
    {
      "id": "contractor1",
      "width": "142pt",
      "height": "60pt",
      "x": "846pt",
      "y": "172pt",
      "font_size": "10pt",
      "padding": "3pt",
      "bold": false,
      "border": true,
      "font_weight": "normal",
      "alignment": "left",
      "default_text": "GENERAL CONTRACTOR:\nADDRESS:\n\nPHONE #:"
    },
    {
      "id": "contractor2",
      "width": "200pt",
      "height": "60pt",
      "x": "988pt",
      "y": "172pt",
      "font_size": "10pt",
      "padding": "3pt",
      "bold": false,
      "border": true,
      "font_weight": "normal",
      "alignment": "left",
      "default_text": ""
    },
    {
      "id": "owner1",
      "width": "142pt",
      "height": "100pt",
      "x": "846pt",
      "y": "18pt",
      "font_size": "10pt",
      "padding": "3pt",
      "bold": false,
      "border": true,
      "font_weight": "normal",
      "alignment": "left",
      "default_text": "OWNER:\nLOCATION:\n\nPROJECT NAME:\n\nCONSULTANT:\nPROJECT NO.:"
    },
    {
      "id": "owner2",
      "width": "200pt",
      "height": "100pt",
      "x": "988pt",
      "y": "18pt",
      "font_size": "10pt",
      "padding": "3pt",
      "bold": false,
      "border": true,
      "font_weight": "normal",
      "alignment": "left",
      "default_text": ""
    }
  ],
  "fixedtext_configs": [
    {
      "id": "subcontractor1",
      "width": "142pt",
      "height": "54pt",
      "x": "846pt",
      "y": "118pt",
      "font_size": "10pt",
      "padding": "3pt",
      "bold": false,
      "border": true,
      "font_weight": "normal",
      "alignment": "left",
      "default_text": "SUBCONTRACTOR<br />ADDRESS:<br /><br />PHONE NO.:<br />"
    },
    {
      "id": "subcontractor2",
      "width": "200pt",
      "height": "54pt",
      "x": "988pt",
      "y": "118pt",
      "font_size": "10pt",
      "padding": "3pt",
      "bold": false,
      "border": true,
      "font_weight": "normal",
      "alignment": "right",
      "default_text": "1775 ROUTE 25:<br />P.O. BOX 430:<br />RIDGE, NY 11961<br />(631) 924-3011 FAX NO.: (631) 924-3275"
    }
  ]
}